---
title: Third Blog Post
author: Xingru Chen, Tong Cheng, Zhuoxi Zheng, Jingyi Gao, Tong Cheng
date: '2022-10-28'
slug: []
categories: []
tags: []
description: Dataset Description
toc: yes
authors: []
series: []
lastmod: '2022-10-28T22:18:59-04:00'
featuredVideo: ~
featuredImage: ~
---
##Justice:

For the “conception” part, I do agree with the argument that the information we want to collect mostly depends on our goal. Based on our group’ s survey, the main question we hope to address is the relationship between income and education, and we need to understand what data is beneficial.
In the “collection” and “dissemination” part, I realized that it is crucial to formulate the content of the questionnaire precisely, which can even avoid duplication in the follow-up process to eliminate unnecessary data.
Also, during the data collection, whenever possible during or after the data collecting process, respect people's choices about the deletion of their personal information.
Finally, members of the community must receive data and study findings in a format they can use.


##Beneficence:
	
It’s important to consider and weight benefits and risks. 
In the acquisition part, income and education can be considered as sensitive topics. Benefits should overweight risks. However, since minimize the amount of PII was collected in the survey, participants don’t have to take high risks. 
In the processing and analysis part, we need to consider participants’ community in order to analysis and interpret the data in order to minimize the risks. In our study, income and education should be interpret respect to participants’ region, age, sex and race.

##Respect for persons: 

Our goal is to analyze the relationship between education level and crime for our dataset.  However, it is also important for us to remind ourselves of the problem of racial disparities in education. We must be acknowledged that one's educational level can depend primarily on race and other identities that impact the amount of power they have in mainstream society while we perform our data analysis. 

##Limitation:

Limitation of the data is that the dataset doesn’t provide any information about participants’ social context and background. It’s important to consider participants’ community when analyzing their income and education. 

##Misuse:

Our dataset reports the total money income of all household members age 15+ during the previous year. The respondents are surveyed throughout the year, and amounts do not reflect calendar year dollars. In other words,  there is a potential for misuse or abuse of the data. Moreover, as we mentioned previously, there is also a possibility for the results to target racial or ethnic minorities, so it is important for us to avoid those situations when getting the results of our analysis.
