---
title: Seventh Blog Post
author: Xingru Chen, Zhuoxi Zhen, Jingyi Gao, Cheng Tong
date: '2022-12-02'
slug: []
categories: []
tags: []
description: Tentative Thesis
toc: yes
authors: []
series: []
lastmod: '2022-12-02T18:35:51-05:00'
featuredVideo: ~
featuredImage: ~
---

## Next Step
Our goal is to construct a model that can accurately forecast future salaries. Education level, gender, age, number of members in a household, number of weeks worked in the previous year, ability to speak English, marital status, ownership of a bathtub or shower, and geographic location are the independent factors that we are interested in. After taking a look at the p-value generated by model 1, we came to the conclusion that "state" should be removed from the model before it is rerun. Because the p-value for some classifications of "state" is higher than 0.05, we will do an analysis of this single variable at a later time. In addition to that, we did some work with the coefficients. For instance, we would like to look into the inequalities between men and women in terms of wage and education.

When both men and women have the same degree of education, our working hypothesis suggests that men will receive higher earnings than women.
